// Code generated by moq; DO NOT EDIT.
// github.com/matryer/moq

package notification

import (
	"sync"
)

var (
	lockSenderMockSend sync.RWMutex
)

// SenderMock is a mock implementation of Sender.
//
//     func TestSomethingThatUsesSender(t *testing.T) {
//
//         // make and configure a mocked Sender
//         mockedSender := &SenderMock{
//             SendFunc: func(msg Message) error {
// 	               panic("TODO: mock out the Send method")
//             },
//         }
//
//         // TODO: use mockedSender in code that requires Sender
//         //       and then make assertions.
//
//     }
type SenderMock struct {
	// SendFunc mocks the Send method.
	SendFunc func(msg Message) error

	// calls tracks calls to the methods.
	calls struct {
		// Send holds details about calls to the Send method.
		Send []struct {
			// Msg is the msg argument value.
			Msg Message
		}
	}
}

// Send calls SendFunc.
func (mock *SenderMock) Send(msg Message) error {
	if mock.SendFunc == nil {
		panic("SenderMock.SendFunc: method is nil but Sender.Send was just called")
	}
	callInfo := struct {
		Msg Message
	}{
		Msg: msg,
	}
	lockSenderMockSend.Lock()
	mock.calls.Send = append(mock.calls.Send, callInfo)
	lockSenderMockSend.Unlock()
	return mock.SendFunc(msg)
}

// SendCalls gets all the calls that were made to Send.
// Check the length with:
//     len(mockedSender.SendCalls())
func (mock *SenderMock) SendCalls() []struct {
	Msg Message
} {
	var calls []struct {
		Msg Message
	}
	lockSenderMockSend.RLock()
	calls = mock.calls.Send
	lockSenderMockSend.RUnlock()
	return calls
}
